/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FullScreenBtn: typeof import('./src/components/FullScreenBtn.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsPicture: typeof import('./src/components/Tabs/TabsPicture.vue')['default']
    TabsVideo: typeof import('./src/components/Tabs/TabsVideo.vue')['default']
    TabsWebCam: typeof import('./src/components/Tabs/TabsWebCam.vue')['default']
    TabsWebRTC: typeof import('./src/components/Tabs/TabsWebRTC.vue')['default']
    VideoRtc: typeof import('./src/components/VideoRtc.vue')['default']
  }
}
